language: generic

os:
  - linux
  - osx

env:
  global:
    - CONDA_PREFIX=$HOME/miniconda
    - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda2-latest"
    - TRAVIS_PYTHON_VERSION="2.7"

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      OS="MacOSX-x86_64"
    else
      OS="Linux-x86_64"
    fi
  - curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
  - bash $HOME/minconda.sh -b -p $CONDA_PREFIX
  - export PATH="$CONDA_PREFIX/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - source activate root
  - conda install python=$TRAVIS_PYTHON_VERSION
  - conda install nose pyyaml netcdf4 markdown basic-modeling-interface -c csdms-stack

install:
  - python setup.py install

script:
  - nosetests

after_success:
  - coveralls --verbose
