ilamb_root:
  description:
    'Path to the ILAMB benchmark data and model output repository (ILAMB_ROOT)'
  value:
    type: string
    default: /home/csdms/ilamb

dest_dir:
  description:
    Directory relative to ILAMB_ROOT where benchmark datasets are stored
  value:
    type: string
    default: DATA

link_dir:
  description:
    Directory relative to ILAMB_ROOT where benchmark datasets are
    linked (optional)
  value:
    type: string
    default: 'DATA-by-project'

study_name:
  description:
    Name of data source; e.g., FLUXNET (optional)
  value:
    type: string
    default: 'PBS'

group_name:
  description:
    "A name under which the uploaded data can be grouped; e.g.,
    your organization ('CSDMS') or your initials ('MDP') (required)"
  value:
    type: string
    default: ''

ingest_files:
  description:
    A list of benchmark data files to ingest
  value:
    type: list
    default: []

make_public:
  description: Allow others to use these benchmark datasets?
  value:
    type: choice
    default: true
    choices:
      - true
      - false

overwrite_files:
  description:
    Overwrite existing files? (Note that base ILAMB files can only be
    modified by an administrator.)
  value:
    type: choice
    default: false
    choices:
      - true
      - false
