ilamb_root:
  description:
    'Path to the ILAMB benchmark data and model output repository (ILAMB_ROOT)'
  value:
    type: string
    default: /home/csdms/ilamb

dest_dir:
  description:
    Directory relative to ILAMB_ROOT where model outputs are stored
  value:
    type: string
    default: MODELS

link_dir:
  description:
    Directory relative to ILAMB_ROOT where model outputs are linked
    (optional)
  value:
    type: string
    default: 'MODELS-by-project'

study_name:
  description:
    Name of modeling project or study; e.g., CMIP5 (optional)
  value:
    type: string
    default: 'PBS'

ingest_files:
  description:
    A list of model output files to ingest
  value:
    type: list
    default: []

make_public:
  description: Allow others to use these model outputs?
  value:
    type: choice
    default: true
    choices:
      - true
      - false
